326/config/routes.rb
WebApp::Application.routes.draw do
  get "/"  => "properties#root"

  resources :properties,
    only: [:index, :edit, :update, :new, :create, :destroy]
end

326/app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :address
  attr_accessible :city
  attr_accessible :state
  attr_accessible :price
  attr_accessible :num_bedrooms
  attr_accessible :num_stories
  attr_accessible :num_square_feet
  attr_accessible :image_url
end

326/app/models/property_admin.rb
class PropertyAdmin < ActiveRecord::Base
  attr_accessible :username
  attr_accessible :password
end

326/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def root
    redirect_to properties_path and return
  end

  def index
    @title = "Properties"
    @properties = Property.order("id")
    render :index and return
  end

  def edit
    @title = "Edit property"
    @property = Property.where(id: params["id"]).first
    render :edit and return
  end

  def update
    @property = Property.find(params["id"])
    @property.address         = params["address"]
    @property.city            = params["city"]
    @property.state           = params["state"]
    @property.price           = params["price"]
    @property.num_bedrooms    = params["num_bedrooms"]
    @property.num_stories     = params["num_stories"]
    @property.num_square_feet = params["num_square_feet"]
    @property.image_url       = params["image_url"]

    if @property.save
      redirect_to properties_path and return
    else
      render :edit and return
    end
  end

  def new
    @title = "Add property"
    @property = Property.new
    render :new and return
  end

  def create
    @property = Property.new
    @property.address         = params["address"]
    @property.city            = params["city"]
    @property.state           = params["state"]
    @property.price           = params["price"]
    @property.num_bedrooms    = params["num_bedrooms"]
    @property.num_stories     = params["num_stories"]
    @property.num_square_feet = params["num_square_feet"]
    @property.image_url       = params["image_url"]

    if @property.save
      redirect_to properties_path and return
    else
      render :new and return
    end
  end

  def destroy
    @property = Property.where(id: params["id"]).first
    @property.destroy
    redirect_to properties_path and return
  end

end

326/app/views/layouts/application.html.erb
<!-- ### Use of flash in default application.html.erb file -->
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= @title %></h1>

<% if @admin %>
  <form method="POST" action="<%= admin_logout_path %>">
    You are logged in as <b><%= @admin.username %></b>.
    <button>Logout</button>
  </form>
  <hr>
<% end %>

<% for flash_type in [:error, :success] %>
  <% if flash[flash_type] %>
    <div class="flash flash-<%= flash_type %>">
      <%= flash[flash_type] %>
    </div>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

326/app/views/properties/_property_form_fields.erb
<% if @property.id %>
  <p>
    <b>ID #: </b><%= @property.id %>
  </p>
<% end %>

<p>
  Address
  <br>
  <%= f.text_field :address %>
</p>

<p>
  Price
  <br>
  <input type="text" name="price" value="<%= @property.price %>"/>
</p>

<p>
  Bedrooms
  <br>
  <input type="text" name="num_bedrooms" value="<%= @property.num_bedrooms %>"/>
</p>

<p>
  Image URL
  <br>
  <input type="text" name="image_url" value="<%= @property.image_url %>" size="80"/>
</p>

<p>
  City
  <br>
  <input type="text" name="city" value="<%= @property.city %>"/>
</p>

<p>
  State
  <br>
  <input type="text" name="state" value="<%= @property.state %>"/>
</p>

<p>
  Number of stories
  <br>
  <input type="text" name="num_stories" value="<%= @property.num_stories %>"/>
</p>

<p>
  Number of square feet
  <br>
  <input type="text" name="num_square_feet" value="<%= @property.num_square_feet %>"/>
</p>

326/app/views/properties/edit.erb
<% if @property.errors.size > 0 %>
  Errors:
  <ul>
  <% for error in @property.errors.full_messages %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<%= form_tag @property do %>
  <input type="hidden" name="_method" value="PUT">

    <%= render :partial => "property_form_fields" %>

    <p>
      <button name="update" value="update">Update</button>
    </p>
<% end %>

326/app/views/properties/index.erb
<table border="1">
  <tr>
    <th>ID #</th>
    <th>Address</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>
  <% for property in @properties %>
    <tr>
      <td><%= property.id %></td>
      <td><%= property.address %></td>
      <td><%= property.price %></td>
      <td>
        <%= link_to "Edit", edit_property_path(property) %>
      </td>
      <td>
        <%= form_tag property_path(property) do %>
          <input type="hidden" name="_method" value="DELETE">
          <button name="delete" value="delete">Delete</button>
        <% end %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td colspan="5">
      <%= link_to "Add new property", new_property_path %>
    </td>
  </tr>
</table>

326/app/views/properties/new.erb
<% if @property.errors.size > 0 %>
  Errors:
  <ul>
  <% for error in @property.errors.full_messages %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<%= render :partial => "property_form_fields" %>